### ISSUE TITLE
[Feedback] Playlet

### ISSUE THREAD

**Issue by TrentStar168** [iBicha/playlet#275] opened 2024-02-01 12:56 UTC
### Feedback
_insert feedback here_

#### App Info
```
{}
```

#### Device Info
```
{}
```

#### Invidious settings
```
{}
```

#### User preferences
```
{}
```

**Comment by iBicha** [comment] 2024-02-01 17:30
It looks like the issue is missing information. Closing

**Closed by iBicha** 2024-02-01 17:30 UTC
