### ISSUE TITLE
Up arrow in remote control is not showing

### ISSUE THREAD

**Issue by TheBossMan3** [iBicha/playlet#237] opened 2023-12-22 18:07 UTC
![IMG_0044](https://github.com/iBicha/playlet/assets/137230614/bfaa0c7d-bfdb-499a-950c-ace57f934f4b)
It’s а pretty small issue but it is driving me insane.
I am on Safari 17.2 on an iPad if that helps

**Comment by iBicha** [comment] 2023-12-22 19:21
Thanks for reporting, I'll look into it

**Comment by iBicha** [comment] 2023-12-22 22:40
It's weird, but I can't reproduce. I pulled out a really old iPad (didn't update in years) and while a lot of things are broken in the page, the remote looked fine.
The [arrow up](https://github.com/iBicha/playlet/blob/cbda8dbf9b206d1181ef1863e312371eadd95d48/playlet-web/src/assets/remote-control/arrow-up.svg.svelte) and [arrow down](https://github.com/iBicha/playlet/blob/cbda8dbf9b206d1181ef1863e312371eadd95d48/playlet-web/src/assets/remote-control/arrow-down.svg.svelte) icons are very similar in structure, I don't know why one would render and the other wouldn't, especially on a modern device

**Comment by iBicha** [comment] 2024-03-04 22:22
@TheBossMan3 following up as a few months has passed, I wonder if a browser update has solved this issue?

**Comment by TheBossMan3** [comment] 2024-03-04 22:51
Let me double check when I get home as I have not used my iPad in a while

**Comment by iBicha** [comment] 2024-04-28 19:39
Closing this for now - I can't find anything that I can do to address it, it's probably an obscure bug in the browser being used.
If this is still persistent, and there's anything to be done to fix it, please reopen the issue

**Closed by iBicha** 2024-04-28 19:39 UTC
Labels: bug, help wanted
