### ISSUE TITLE
503 service unavailable

### ISSUE THREAD

**Issue by istovits** [iBicha/playlet#506] opened 2024-12-16 22:01 UTC
same as last week. nothing loads and cannot navigate to settings with the remote,only the home button works to escape.

**Comment by iBicha** [comment] 2024-12-16 23:19
> same as last week. nothing loads

[invidious.nerdvpn.de](https://invidious.nerdvpn.de/) is down. You will need to change the instance. I understand that there aren't a lot of instances available. Not a lot I can do right now. From https://api.invidious.io it seems that only [inv.nadeko.net](https://inv.nadeko.net/) can be usable but it has no CORS support, so the web app will not load some feeds properly.

> and cannot navigate to settings with the remote,only the home button works to escape.

```
If the remote control is not working, please check your device settings. Go to:
- Settings
- System
- Advanced System Settings
- Control by mobile apps
- Network access
And set it to "Enabled".
```

**Comment by istovits** [comment] 2024-12-17 05:56
it may be tied to nerdvpn being down. the remote works everywhere else.

**Comment by tcrenegade50** [comment] 2024-12-17 10:52
> > same as last week. nothing loads
> 
> [invidious.nerdvpn.de](https://invidious.nerdvpn.de/) is down. You will need to change the instance. I understand that there aren't a lot of instances available. Not a lot I can do right now. From https://api.invidious.io it seems that only [inv.nadeko.net](https://inv.nadeko.net/) can be usable but it has no CORS support, so the web app will not load some feeds properly.
> 
> I'm working on making Playlet work a bit more independently from Invidious #502 (in hopes it prevent instance specific issues) but it will take some time to get there.
> 
> > and cannot navigate to settings with the remote,only the home button works to escape.
> 
> ```
> If the remote control is not working, please check your device settings. Go to:
> - Settings
> - System
> - Advanced System Settings
> - Control by mobile apps
> - Network access
> And set it to "Enabled".
> ```

I can confirm this worked for me. Just put in the URL manually

**Comment by tcrenegade50** [comment] 2024-12-17 11:02
> same as last week. nothing loads and cannot navigate to settings with the remote,only the home button works to escape.

I was having the same problem but I found the remote wasn't actually locked up, it had an extreme delay to it and was really easy to crash because of it. I found a solution though. When you get your first 503 error screen don't press any buttons besides the down button. Hold this until you scroll past all of the code and get to the "OK" at the bottom. This took me about 3 minutes to do the first time I tried. After I hit On "OK", the remote was no longer locked up and the lag was gone.

 Also the instance mentioned by iBicha is not viewable on the public instance list on the app. Manually edit the instance till it reads https://inv.nadeko.net

**Comment by iBicha** [comment] 2024-12-18 00:08
The maintainer for [invidious.nerdvpn.de](https://invidious.nerdvpn.de/) has removed their instance from the list of public instances.
> Reason: Won't be able to fix the current YT blockage until after Christmas, simply don't hve the time right now.

This leaves https://inv.nadeko.net to be the only public instance available left (that is usable from an API.) so it was set as a default in Playlet to avoid confused users (who are not familiar with Invidious instances.) and a new version has been released.
Because this instance doesn't support CORS as you can see on https://api.invidious.io/ this means the video feeds will not load in the web app.

Closing, since as I mentioned, I can't do much more than this right now.

**Closed by iBicha** 2024-12-18 00:08 UTC
Labels: bug

**Comment by tcrenegade50** [comment] 2024-12-21 08:22
I know this issue is closed but I just wanted to make an update as it appears https://inv.nadeko.net/ is now also down, at least for playlet users. I'm getting a 401 code "No Authorized" Requestld: 122683837 Body: API disabled.

Another instance is now available  , invidious.jing.rocks, but they appear to be having trouble as I'm getting a code 500 from them in regards to an internal server error
