### ISSUE TITLE
[Feedback] Playlet issue with mobile (public instance with no CORS)

### ISSUE THREAD

**Issue by mindfreaak** [iBicha/playlet#96] opened 2023-06-29 13:06 UTC
### Feedback
Video search on mobile doesn't work.

To reproduce:
- scan QR
- go to search
- type any text and press search button on the keyboard

(Google pixel 5)

#### App Info
```
{
  "git_commit_hash": "90ccb4080c02927a13a2af52636e4187b70e1c4c",
  "id": "693751",
  "lib_git_commit_hash": "cc78fb0ec1d61f2aaa95ca8d73606b0496874ab5",
  "lib_url": "https://github.com/iBicha/playlet/releases/latest/download/playlet-lib.zip",
  "lib_url_type": "github",
  "lib_version": "0.10.1",
  "lib_version_latest": "0.10.1",
  "version": "0.10.0"
}
```

#### Device Info
```
{
  "display_aspect_ratio": "16x9",
  "display_mode": "720p",
  "display_size": {
    "h": 720,
    "w": 1280
  },
  "display_type": "HDTV",
  "friendly_name": "65\" TCL Roku TV",
  "graphics_platform": "opengl",
  "internet_status": true,
  "model": "7000X",
  "model_details": {
    "Manufacturer": "TCL",
    "ModelNumber": "7133X",
    "ScreenSize": 65,
    "VendorName": "TCL",
    "VendorUSBName": "Longview_TCL_TCL_YN"
  },
  "model_display_name": "65S423-CA",
  "model_type": "TV",
  "os_version": {
    "build": "4182",
    "major": "12",
    "minor": "0",
    "revision": "0"
  },
  "ui_resolution": {
    "height": 1080,
    "name": "FHD",
    "width": 1920
  },
  "user_country_code": "CA",
  "video_mode": "2160p60"
}
```

#### Invidious settings
```
{
  "auth_url": "http://iv.ggtyler.dev/authorize_token?scopes=GET%3Afeed%2CGET%3Aplaylists%2CPOST%3Atokens%2Funregister%2CPOST%3Ahistory*&callback_url=http%3A%2F%2F192.168.0.127%3A8888%2Finvidious%2Ftoken_callback%3Fref%3Dhttps%3A%2F%2Fiv.ggtyler.dev&expire=1751115736",
  "backup_instances": [
    "https://vid.puffyan.us",
    "https://y.com.sb",
    "https://invidious.tiekoetter.com",
    "https://inv.bp.projectsegfau.lt",
    "https://invidious.flokinet.to"
  ],
  "current_instance": "https://iv.ggtyler.dev",
  "logged_in": false,
  "logged_in_instance": null,
  "logged_in_username": null
}
```

#### User preferences
```
{
  "__version": 1,
  "invidious.instance": "https://iv.ggtyler.dev",
  "invidious.proxy_videos": "if_needed",
  "playback.autoplay": true,
  "playback.preferred_quality": "auto",
  "sponsorblock.enabled": true,
  "sponsorblock.show_notifications": true
}
```

**Comment by iBicha** [comment] 2023-06-29 13:19
Thanks for sharing the feedback
I can reproduce the issue. Looking at https://iv.ggtyler.dev, it seems to be a CORS issue.
The API does not allow any origin. This needs to be addressed in someway, by testing instances before using them for example.

**Comment by iBicha** [comment] 2023-09-07 22:11
Instances not supporting CORS are now filtered out.

**Closed by iBicha** 2023-09-07 22:11 UTC
Labels: bug
