### ISSUE TITLE
[REQUEST] Resume playback?

### ISSUE THREAD

**Issue by KatttTheFemboi** [iBicha/playlet#429] opened 2024-07-22 18:10 UTC
Hi, I was wondering if you could add resume playback? Possibly by storing it on the device? It gets a bit annoying having to remember where I was but if this isn’t possible to add I understand

**Comment by iBicha** [comment] 2024-07-22 18:16
Duplicate of #138 
I've started working on this last year #236, but never got the chance to finish it. No ETA unfortunately.

**Closed by iBicha** 2024-07-22 18:16 UTC
Labels: duplicate
